name: Pages & PDF

on:
  push:
    branches:
      - master  # default branch
    tags:
      - '*'

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: write   # to upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: sudo apt install -y pandoc context
      - name: Build
        run: make all
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Move html
        run: |
          mkdir upload
          mv output/resume.html upload/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'upload'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Release PDF
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.pdf"
